posted:
- amazon_link: https://amzn.to/47JsGpU
  eyecatch: true
  illustrations: 5
  note_url: https://note.com/jinseikaiteki/n/n036f0ea89c5d
  posted_at: '2026-04-15T07:30:00+09:00'
  slug: amazon-basics-aa-battery-review
  version: sakura_v6_white_futuristic_bangs
- amazon_link: https://amzn.to/4eorbkN
  eyecatch: true
  illustrations: 5
  note_url: https://note.com/jinseikaiteki/n/nea8cab9de6c6
  posted_at: '2026-04-15T08:10:00+09:00'
  slug: deoway-card-case-review
  version: sakura_v6_white_futuristic_bangs
- note_url: https://editor.note.com/notes/nd62309e9492d/publish/
  posted_at: '2026-04-15T11:03:42.927890+00:00'
  slug: yamazaki-unit-bath-brush-review
- note_url: https://editor.note.com/notes/n33246351304f/publish/
  posted_at: '2026-04-15T22:09:08.435264+00:00'
  slug: final-ze500-asmr-3d-review
- note_url: https://editor.note.com/notes/nefdc51f1b663/publish/
  posted_at: '2026-04-16T21:47:06.890131+00:00'
  slug: anker-powerbank-25000-builtin-cable-review
- note_url: https://editor.note.com/notes/n9b11c6841350/publish/
  posted_at: '2026-04-16T21:59:50.249544+00:00'
  slug: fedour-aquarium-air-pump-review
- note_url: https://editor.note.com/notes/n58c2bcab8737/publish/
  posted_at: '2026-04-17T23:01:27.242416+00:00'
  slug: 100w-usb-charger-comparison-2026
- note_url: https://editor.note.com/notes/nfd7ea0b9741b/publish/
  posted_at: '2026-04-17T23:02:43.140386+00:00'
  slug: amazon-disaster-kit-b0ct7zx2ch-review
- note_url: https://editor.note.com/notes/nea0448dae5d6/publish/
  posted_at: '2026-04-17T23:04:13.564514+00:00'
  slug: amazon-sale-guide-2026
- note_url: https://editor.note.com/notes/n201fa6d8b4d1/publish/
  posted_at: '2026-04-18T23:01:27.455463+00:00'
  slug: 3d-printer-comparison-2026
- note_url: https://editor.note.com/notes/nd9f27595747a/publish/
  posted_at: '2026-04-18T23:02:35.103927+00:00'
  slug: anker-317-charger-100w-review
- note_url: https://editor.note.com/notes/n24475f9cd2d4/publish/
  posted_at: '2026-04-19T11:01:14.771727+00:00'
  slug: amazon-basics-monitor-arm-review
- note_url: https://editor.note.com/notes/nf6ff138103a1/publish/
  posted_at: '2026-04-21T14:18:41.923109+00:00'
  slug: anker-nano-charger-100w-review
- note_url: https://editor.note.com/notes/nb7cfeacacf5c/publish/
  posted_at: '2026-04-21T23:00:43.476246+00:00'
  slug: anker-prime-charger-100w-review
- note_url: https://editor.note.com/notes/n15b2650b185e/publish/
  posted_at: '2026-04-22T03:00:50.639250+00:00'
  slug: anker-soundcore-liberty5-review
